# -*- coding: utf-8 -*-
"""movieapp.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19RktAtRPG4l90WoJhB6JYJ0H_ZYuLux8
"""

import numpy as np
import pandas as pd
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity
import streamlit as st
import matplotlib.pyplot as plt
import seaborn as sns

st.set_page_config(layout="wide") # Use wide layout

st.title('🎬 Movie Recommendation System')l


movies_data = pd.read_csv('/content/imdb_movies_2024.csv')

st.markdown("---")

# Data Overview - placed in an expander
with st.expander("📚 View Original Movie Data Sample"):
    st.markdown("A glimpse of the dataset used for recommendations.")
    st.dataframe(movies_data.head(10), use_container_width=True) # Use container width

st.markdown("---")

storline_data = movies_data['Storyline']


vectorizer = TfidfVectorizer()
feature_vectors = vectorizer.fit_transform(storline_data)


similarity = cosine_similarity(feature_vectors)

st.header('🔍 Find Your Next Movie') # Better header for input section
storyline = st.text_input('Enter a storyline or a description of a movie you enjoyed:', '')

if storyline:
    st.subheader('🌟 Top Movie Recommendations Based on Your Input:')


    input_storyline_vector = vectorizer.transform([storyline])


    similarity_score_with_input = cosine_similarity(input_storyline_vector, feature_vectors)


    similarity_scores = list(enumerate(similarity_score_with_input[0]))


    sorted_similar_movies = sorted(similarity_scores, key=lambda x: x[1], reverse=True)


    plot_data = []
    top_recommendations = []
    for i, (movie_index, score) in enumerate(sorted_similar_movies):
        if i < 10:
            title = movies_data.iloc[movie_index]['Movie Name']
            full_storyline = movies_data.iloc[movie_index]['Storyline'] # Get full storyline
            plot_data.append({'Rank': i + 1, 'Movie Name': title, 'Similarity Score': score})
            top_recommendations.append({'Rank': i + 1, 'Movie Name': title, 'Storyline': full_storyline, 'Similarity Score': score})
        else:
            break

    if top_recommendations:
        col1, col2 = st.columns([2, 3])

        with col1:
            st.markdown("### Recommended Movies (Details)")
            for rec in top_recommendations:
                st.markdown(f"---")
                st.markdown(f"**{rec['Rank']}. {rec['Movie Name']}**")
                st.markdown(f"Similarity: `{rec['Similarity Score']:.4f}`")
                st.info(f"*{rec['Storyline']}*")
            st.markdown("---")

        with col2:
            st.markdown("### Visual Summary")
            plot_df = pd.DataFrame(plot_data)


            fig = plt.figure(figsize=(10, 6))
            sns.barplot(x='Similarity Score', y='Movie Name', data=plot_df.sort_values(by='Similarity Score', ascending=False), palette='viridis', hue='Movie Name', legend=False)
            plt.title('Top 10 Movie Recommendations by Storyline Similarity', fontsize=14)
            plt.xlabel('Cosine Similarity Score', fontsize=10)
            plt.ylabel('Movie Name', fontsize=10)
            plt.xlim(0, 1.05)
            plt.xticks(fontsize=8)
            plt.yticks(fontsize=8)
            plt.grid(axis='x', linestyle='--', alpha=0.7)
            plt.tight_layout()
            st.pyplot(fig, use_container_width=True)
    else:
        st.warning("No similar movies found for your storyline. Please try a different input.")


st.sidebar.markdown("---")
st.sidebar.write("Developed by DHANUSH DB")